### PR TITLE
Fix images throughout

### LINKED ISSUE #2392: Figures are missing in the User's Guide (development version)
It seems like a recent build of the documentation has caused the figures to go missing.  E.g., the figures for SP and BGC spinup are missing:

https://escomp.github.io/ctsm-docs/versions/master/html/users_guide/running-special-cases/Spinning-up-the-Satellite-Phenology-Model-CLMSP-spinup.html

https://escomp.github.io/ctsm-docs/versions/master/html/users_guide/running-special-cases/Spinning-up-the-biogeochemistry-BGC-spinup.html

The CLM5 version appears to be ok.
Is this in process of being fixed maybe?

### PR DESCRIPTION
**Pull request by samsrabin**
Resolves ESCOMP/CTSM#2392.

### CODE REVIEW

**Comment by samsrabin** [comment]
Seems to have deleted the tillage instructions.

**Review by olyson — COMMENTED** [review]
The images aren't rendering, but it looks like they are all there.  I compared the list here to the ones in my recent build.

**Comment by samsrabin** [comment]
@olyson I'm concerned that they're not rendering for you. Do you mean when you check out this branch locally and open an HTML file from there?

**Comment by olyson** [comment]
No, when I look in github at the files that have changed, I see, for example,

Binary file modifiedBIN +138 KB (110000%) 
[versions/master/html/_images/CLM4_vertsoil_soilstruct_drawing.png](https://github.com/ESCOMP/ctsm-docs/pull/4/files#diff-6d4d42ad21cb1d99be9f0908ac728a47f5a4371f6517bc7bbc11dfcee12ada7b)

Unable to render rich display

Invalid image source.

But maybe they aren't supposed to render in github?

**Comment by samsrabin** [comment]
Ok yeah, I see the same thing. I think that's just because it's trying to show the diff, but the "before" is an incomplete/corrupted file. If you go to ... > View File, it's there.

**Comment by samsrabin** [comment]
By the way, it's currently up-to-date with commit [14ad3e3](https://github.com/ESCOMP/CTSM/pull/2394/commits/14ad3e3952f35c2352c9d65ada23f353b633b428) in ESCOMP/CTSM#2394.

**Comment by olyson** [comment]
Got it, thanks.

**Comment by olyson** [comment]
This one looks weird, there's a background pattern:

https://github.com/ESCOMP/ctsm-docs/blob/47a5d56845694969f82d7007034c9b2140409178/versions/master/html/_images/ctsm_lilac_runtime_file_workflow.svg

**Comment by samsrabin** [comment]
That's okay; that background is just to indicate where the file is transparent. It looks fine in the rendered HTML. (Might be an issue if someone's machine is in dark mode, though...)

**Comment by samsrabin** [comment]
@olyson, are you okay with this coming in?

**Comment by olyson** [comment]
Yes, thanks.

**Pull request merged**
