### PR TITLE
Update nofates and fates history variable lists (and other things apparently)

### PR DESCRIPTION
**Pull request by olyson**
This was originally a PR to update the nofates and fates history variable lists as the documentation part of https://github.com/ESCOMP/CTSM/pull/2512.  But after building the documentation it is reporting a great number of other changes.  E.g., some new User's Guide stuff on meshes.
So, I'm wondering it there is a branch somewhere that has this stuff that maybe wasn't built and pushed to gh-pages?  Or maybe I've done things wrong here?

### CODE REVIEW

**Comment by samsrabin** [comment]
Nah, you're probably right. If it builds without (unexpected/new) errors, you're good to merge.

**Comment by olyson** [comment]
Well, actually, I do see some build warnings associated with the new mesh instructions.  There seems to be a how-to-make-mesh.md file that is by itself in the source directory.

**Comment by samsrabin** [comment]
Yeah, that's a known issue: ESCOMP/CTSM#2489. I think it's probably better to go ahead and get the documentation up, even it's it's formatted badly, than to wait for us to fix it.

**Comment by olyson** [comment]
Makes sense, thanks.

**Pull request merged**
